# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GGDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Database'

pod 'ARSLineProgress', '~> 2.0'

end
